# Enable Blast Radius in-game
# This could be changed to false 
# if you have created your own plugin using BlastRadius
enable-br-effects: true

# Allow fires to randomly spawn from TNT
blast-fires: true

# Allow smoke to spawn randomly from TNT
# Performance Impact
blast-smoke: true

# Obliterate Obliterables
# All objects to obliterate will not drop their items naturally
obliterate-obliterables: false

# Blast Radius in Blocks
# The blast radius is elliptical
# Larger the radius, the more of a impact it has on performance
# Valid Radiuses: 5 - 15
# Default: 10
blast-radius: 10

# Fire Radius in Blocks
# The blast radius is elliptical
# Valid Radiuses: 5 - 15
# Default: 9
fire-radius: 9

# Smoke particle count per spawn
# More particles = more of a impact on performance
smoke-count: 10

# Smoke X,Y,Z Offset
# Must be below 1.5
# Defauilt: 0.25
smoke-offset: 0.25

# Inner Radius Materials
# For doubling chances of type, just add it twice, or three times... or? 
inner-blast-materials:
 - AIR
 - GRAVEL
 - OBSIDIAN
 - NETHERRACK
 - COBBLESTONE 
 
# Outer Blast Radius Materials
outer-blast-materials:
 - GRAVEL
 - COBBLESTONE
 - DIRT
 
# Protected Materials
# These materials will not be touched at all
# This includes the random fire spawns (Except form fire spread)
protected-materials:
 - BEDROCK
 - WATER
 - STATIONARY_LAVA
 - STATIONARY_WATER
 - TNT
 - EXPLOSIVE_MINECART
 - ARMOR_STAND
 - BREWING_STAND
 - CHEST
 - ENDER_CHEST
 - STRUCTURE_BLOCK
 - COMMAND
 - COMMAND_CHAIN
 - COMMAND_MINECART
 - COMMAND_REPEATING
 - IRON_ORE
 - DIAMOND_ORE
 - COAL_ORE
 - GOLD_ORE
 - EMERALD_ORE
 - IRON_BLOCK
 - IRON_FENCE
 - IRON_DOOR_BLOCK
 - IRON_DOOR
 - IRON_PLATE
 - IRON_TRAPDOOR
 - GOLD_BLOCK
 - DIAMOND_BLOCK
 
# Obliterate Materials
# These materials will be set to AIR
# Subsequently they will break naturally if obliterate-obliterables is false
obliterate-materials:
 - YELLOW_FLOWER
 - LONG_GRASS
 - FLOWER_POT
 - DEAD_BUSH
 - PUMPKIN_STEM
 - SAPLING
 - TRAP_DOOR
 - ACACIA_DOOR
 - ACACIA_DOOR_ITEM
 - ACACIA_FENCE
 - ACACIA_FENCE_GATE
 - ACACIA_STAIRS
 - BIRCH_DOOR
 - BIRCH_DOOR_ITEM
 - BIRCH_FENCE
 - BIRCH_FENCE_GATE
 - BIRCH_WOOD_STAIRS
 - BOAT
 - BOAT_ACACIA
 - BOAT_BIRCH
 - BOAT_DARK_OAK
 - BOAT_JUNGLE
 - BOAT_SPRUCE
 - DARK_OAK_DOOR
 - DARK_OAK_DOOR_ITEM
 - DARK_OAK_FENCE
 - DARK_OAK_FENCE_GATE
 - DARK_OAK_STAIRS
 - GLASS
 - JUNGLE_DOOR
 - JUNGLE_DOOR_ITEM
 - JUNGLE_FENCE
 - JUNGLE_FENCE_GATE
 - JUNGLE_WOOD_STAIRS
 - LADDER
 - LEAVES
 - LEAVES_2
 - LOG
 - LOG_2
 - SIGN
 - SIGN_POST
 - SPONGE
 - SPRUCE_DOOR
 - SPRUCE_DOOR_ITEM
 - SPRUCE_FENCE
 - SPRUCE_FENCE_GATE
 - SPRUCE_WOOD_STAIRS
 - STAINED_GLASS
 - STAINED_GLASS_PANE
 - STRING
 - SUGAR_CANE_BLOCK
 - THIN_GLASS
 - TORCH
 - TRAP_DOOR
 - TRAPPED_CHEST
 - TRIPWIRE
 - TRIPWIRE_HOOK
 - VINE
 - WALL_BANNER
 - WALL_SIGN
 - WATER_LILY
 - WEB
 - WHEAT
 - WOOD
 - WOOD_BUTTON
 - WOOD_DOOR
 - WOOD_DOUBLE_STEP 
 - WOOD_PLATE
 - WOOD_STAIRS
 - WOOD_STEP
 - WORKBENCH